# Generated by Django 4.0.3 on 2022-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=256)),
                ('default_language', models.CharField(choices=[('PT', 'Portuguese'), ('EN', 'English'), ('KR', 'Korean'), ('JP', 'Japanese')], default='EN', max_length=2)),
                ('default_pool_id', models.CharField(default='pool1ndtsklata6rphamr6jw2p3ltnzayq3pezhg0djvn7n5js8rqlzh', max_length=56)),
            ],
        ),
    ]
