# Generated by Django 4.0.3 on 2022-04-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardabot', '0002_chat_client'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('chat_id', 'client')},
        ),
    ]
