# Generated by Django 4.0.3 on 2022-05-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardabot', '0003_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='default_language',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
