# Generated by Django 4.0.3 on 2022-06-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardabot', '0007_chat_tmp_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsignedTransaction',
            fields=[
                ('tx_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('tx_cbor', models.CharField(max_length=4096)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=17)),
                ('username_receiver', models.CharField(max_length=32)),
                ('receiver_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_chat', to='cardabot.chat')),
                ('sender_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_chat', to='cardabot.chat')),
            ],
        ),
    ]
