# Generated by Django 4.0.3 on 2022-06-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardabot', '0008_unsignedtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsignedtransaction',
            name='username_receiver',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
