# Generated by Django 4.0.3 on 2022-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardabot', '0009_alter_unsignedtransaction_username_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsignedtransaction',
            name='username_receiver',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
